// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: logs/logs.proto

package logs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_logs_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_logs_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_logs_logs_proto protoreflect.FileDescriptor

const file_logs_logs_proto_rawDesc = "" +
	"\n" +
	"\x0flogs/logs.proto\x12\x04logs\x1a\x1cgoogle/api/annotations.proto\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"$\n" +
	"\fListResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines2N\n" +
	"\vLogsService\x12?\n" +
	"\x04List\x12\x11.logs.ListRequest\x1a\x12.logs.ListResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/logsB.Z,github.com/unix4ever/fe-test-server/api/logsb\x06proto3"

var (
	file_logs_logs_proto_rawDescOnce sync.Once
	file_logs_logs_proto_rawDescData []byte
)

func file_logs_logs_proto_rawDescGZIP() []byte {
	file_logs_logs_proto_rawDescOnce.Do(func() {
		file_logs_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_logs_proto_rawDesc), len(file_logs_logs_proto_rawDesc)))
	})
	return file_logs_logs_proto_rawDescData
}

var file_logs_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logs_logs_proto_goTypes = []any{
	(*ListRequest)(nil),  // 0: logs.ListRequest
	(*ListResponse)(nil), // 1: logs.ListResponse
}
var file_logs_logs_proto_depIdxs = []int32{
	0, // 0: logs.LogsService.List:input_type -> logs.ListRequest
	1, // 1: logs.LogsService.List:output_type -> logs.ListResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logs_logs_proto_init() }
func file_logs_logs_proto_init() {
	if File_logs_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_logs_proto_rawDesc), len(file_logs_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_logs_proto_goTypes,
		DependencyIndexes: file_logs_logs_proto_depIdxs,
		MessageInfos:      file_logs_logs_proto_msgTypes,
	}.Build()
	File_logs_logs_proto = out.File
	file_logs_logs_proto_goTypes = nil
	file_logs_logs_proto_depIdxs = nil
}
