kind: golang.Generate
spec:
  baseSpecPath: /api
  vtProtobufEnabled: true
  specs:
    - source: https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/http.proto
      subdirectory: google/api/
      genGateway: true
    - source: https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto
      subdirectory: google/api/
      genGateway: true
    - source: api/logs/logs.proto
      subdirectory: logs
      genGateway: true
---
kind: auto.CustomSteps
spec:
  steps:
    - name: openapi-gen
      toplevel: true
---
kind: golang.Build
name: server
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
    darwin-amd64:
      GOOS: darwin
      GOARCH: amd64
    darwin-arm64:
      GOOS: darwin
      GOARCH: arm64
